spring:
  datasource:
    # ??? ??? ?? XE ?? FREE? ??? ??? ? ????.
    # gvenzl/oracle-xe 21c? ????? FREE? ?????.
    url: jdbc:oracle:thin:@oracle-db:1521/FREE
    username: onecore
    password: onecore
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Oracle 12c ??? ?? ??? ????? ??
        dialect: org.hibernate.dialect.OracleDialect